### ISSUE TITLE
Not generating icons

### ISSUE THREAD

**Issue by BenjaminFaal** [IanMercer/imagemultiplier#11]
Hey,

Please could you help me, its not generating the icons.

This is my file: 
# This is a sample Image Multiplier specification file
# In here you define each of the output types you want to create
# And then provide search expressions for the SVG files you want to process
# Each SVG file is processes against the matching type specifiers to create
# multiple PNG files in all of the sizes you need for your Android and iOS projects

{ type: 'AndroidIcon', width: 36, color: '#f80c12', path: 'Android/Resources/drawable-ldpi/{0}' }
{ type: 'AndroidIcon', width: 48, color: '#f80c12', path: 'Android/Resources/drawable-mdpi/{0}' }
{ type: 'AndroidIcon', width: 72, color: '#f80c12', path: 'Android/Resources/drawable-hdpi/{0}' }
{ type: 'AndroidIcon', width: 96, color: '#f80c12', path: 'Android/Resources/drawable-xhdpi/{0}' }
{ type: 'AndroidIcon', width: 96, color: '#f80c12', path: 'Android/Resources/drawable/{0}' }

{ type: 'iosIcon', width:  32, path: 'iOS/Resources/{0}@1x' }
{ type: 'iosIcon', width:  29, path: 'iOS/Resources/{0}29@1x' }
{ type: 'iosIcon', width:  57, path: 'iOS/Resources/{0}57@1x' }
{ type: 'iosIcon', width:  58, path: 'iOS/Resources/{0}29@2x' }
{ type: 'iosIcon', width:  80, path: 'iOS/Resources/{0}40@2x' }
{ type: 'iosIcon', width: 114, path: 'iOS/Resources/{0}57@2x' }
{ type: 'iosIcon', width: 120, path: 'iOS/Resources/{0}60@2x' }

{ type: 'TabIcon', width: 52, color: '#f80c12', path: 'Android/Resources/drawable-ldpi{0}' }
# You can process multiple directories, each with different type specifiers

{ process: './*.svg', as: ['AndroidIcon', 'iosIcon'] }

I have an icon.svg file one folder above the default.multiplier file which is in the main project folder.

**Comment by IanMercer** [comment]
If your SVG file is one folder above the multiplier file you'd need to use `../*.svg` in the process instruction.

**Comment by BenjaminFaal** [comment]
Im sorry its still now working.

**Comment by Korayem** [comment]
Same here, it's not working at all
