### ISSUE TITLE
Support colorization of SVG files. 

### ISSUE THREAD

**Issue by awolf** [IanMercer/imagemultiplier#3]
I see in the code that the colorization of SVG files is commented out and has a "// TODO: This is not yet working" comment on it. Will you be adding this in the future? 

or 

Would you suggest we remove the color from the specification and have color specific named SVG's and Icons?

PS. Blog post is in the works!

**Comment by IanMercer** [comment]
For the moment, you can have multiple SVGs of different colors and process each of them.

I do plan to add this feature as it's quite useful to have a single SVG input and to create active and disabled icons from it.
